# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="eagle"
ZSH_THEME="agnoster"

[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

export EDITOR='vim'

exit() {
    if [[ -z $TMUX ]]; then
        builtin exit
    else
        tmux detach
    fi
}

alias work='get-shit-done work'
alias play='get-shit-done play'

alias git=hub

# http://zshwiki.org/home/builtin/functions/zmv
autoload -U zmv

# Get Shit Done setup
alias get-shit-done="~/environment/get-shit-done/get-shit-done"

# Todo.txt setup
#export TODOTXT_DEFAULT_ACTION=ls
#export TODOTXT_SORT_COMMAND='env LC_COLLATE=C sort -k 2,2 -k 1,1n'
alias t="~/environment/todo.txt-cli/todo.sh -d $HOME/Dropbox/todo/todo.cfg"
alias todo="t"

# ls() {
    # if [[ -f ./.lsrc ]]; then
        # /bin/ls `cat .lsrc` $*
    # else
        # /bin/ls $*
    # fi
# }

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"


# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"
#

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git tmuxinator ssh-agent ruby)

source $ZSH/oh-my-zsh.sh

# https://wiki.archlinux.org/index.php/Sudo#Passing_aliases
alias sudo='nocorrect sudo '

# Customize to your needs...
export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin
#export PATH=$PATH:/Users/nateeagle5/environment/submodules/get-shit-done

# enable rbenv shims and autocompletion
#eval "$(rbenv init -)"

# http://superuser.com/questions/397362/zsh-expansion-for-a-timestamp/409429#409429
function unix_ts { LBUFFER="${LBUFFER}$(date '+%Y%m%d%H%M%S')" }
zle -N unix_ts
bindkey "^t" unix_ts

alias gr=$(git rev-parse --show-toplevel)

export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).
export HOMEBREW_GITHUB_API_TOKEN=ca6b578264c5730ffaa80ea878b49369d26ae5b5

# Zsh custom completions
fpath=(~/.zsh/completions $fpath) 
autoload -U compinit && compinit
